version: "3.7"
services:
  app:
    build:
      args:
        user: barnacle
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: barnacle
    container_name: barnacle-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - barnacle

  mysql:
    image: mysql:8.0
    container_name: barnacle-mysql
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - './docker/volumes/db:/var/lib/mysql'
      - './docker-compose/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - barnacle

  nginx:
    image: nginx:1.17-alpine
    container_name: barnacle-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - barnacle

networks:
  barnacle:
    driver: bridge
